spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:coupon_prd}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: ${DB_USERNAME:template}
    password: ${DB_PASSWORD:template}
  sql:
    init:
      mode: never

logging:
  level:
    root: warn
    com.kojuju.coupon: info
